//! Engine-neutral CPU execution contracts.
//!
//! This crate owns the boundary between runtime orchestration and CPU execution
//! implementations. It deliberately has no dependency on runtime, Horizon,
//! scheduler, graphics, application configuration, compiler, or host
//! virtualization APIs.

use core::fmt::{self, Display, Formatter};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};

use nixe_cpu::coverage::CoverageId;
use nixe_cpu::error::{InstructionFetchFault, ProfileDisabledInstruction, UnallocatedEncoding};
use nixe_cpu::exception::ExceptionKind;
use nixe_cpu::location::{InstructionEncoding, LocationDescriptor};
use nixe_cpu::memory::{CpuMemory, DataAccessFault};
use nixe_cpu::profile::{GuestCpuProfile, ProcessCpuContext};
use nixe_cpu::state::{RegisterContext, ThreadCpuState};
use nixe_memory::{AddressSpaceId, CanonicalRangeTranslator, GuestVirtualAddress};

mod capability;
mod conformance;
mod control;
pub use capability::{
    CapabilityRejection, CapabilityRejectionReason, CapabilityReport, EngineCapabilities,
    EngineDescriptor, EngineKind,
};
pub use conformance::{
    CONFORMANCE_FALLBACK_ENCODING, ConformanceCase, ConformanceFailure, ConformanceReport,
    run_provider_conformance,
};
pub use control::{ControlSnapshot, CrossVcpuRequest, EngineControl, EngineExecutionGuard};

macro_rules! identity {
    ($name:ident) => {
        #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        pub struct $name(u64);

        impl $name {
            #[must_use]
            pub const fn new(value: u64) -> Self {
                Self(value)
            }

            #[must_use]
            pub const fn get(self) -> u64 {
                self.0
            }
        }
    };
}

identity!(EngineId);
identity!(EngineDomainId);
identity!(EngineExecutorId);

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct TimerSnapshot {
    pub counter: u64,
    pub frequency: u64,
}

pub trait EngineTimer {
    fn snapshot(&self) -> TimerSnapshot;
}

/// Physical-vCPU event and interrupt state shared by every engine provider.
///
/// The event register belongs to the emulated processing element rather than
/// a guest thread or one engine domain. Runtime owns this object and lends it
/// to the executor selected for each slice.
#[derive(Clone, Default)]
pub struct VcpuEventState {
    state: Arc<VcpuEventStateInner>,
}

#[derive(Default)]
struct VcpuEventStateInner {
    event_register: AtomicBool,
    pending_interrupts: AtomicU32,
}

impl VcpuEventState {
    /// Sets the local event register, as generated by SEV, SEVL, or an
    /// interrupt becoming pending.
    pub fn signal_event(&self) {
        self.state.event_register.store(true, Ordering::Release);
    }

    /// Atomically tests and clears the local event register for WFE.
    #[must_use]
    pub fn consume_event(&self) -> bool {
        self.state.event_register.swap(false, Ordering::AcqRel)
    }

    /// Publishes one or more runtime-normalized interrupt sources.
    pub fn post_interrupts(&self, mask: u32) {
        if mask == 0 {
            return;
        }
        self.state
            .pending_interrupts
            .fetch_or(mask, Ordering::Release);
        self.signal_event();
    }

    /// Returns whether WFI has a pending wake source without consuming it.
    #[must_use]
    pub fn interrupts_pending(&self) -> bool {
        self.state.pending_interrupts.load(Ordering::Acquire) != 0
    }

    /// Transfers pending interrupt sources to one normalized engine exit.
    #[must_use]
    pub fn take_pending_interrupts(&self) -> u32 {
        self.state.pending_interrupts.swap(0, Ordering::AcqRel)
    }
}

/// Scheduler-visible action requested by one retired architectural hint.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SchedulerRequest {
    Yield,
    WaitForEvent,
    WaitForInterrupt,
    SendEvent,
}

/// One bounded request. Borrowed resources cannot escape the call.
pub struct RunRequest<'a> {
    pub cpu: ProcessCpuContext,
    pub memory: &'a dyn CpuMemory,
    pub state: &'a mut ThreadCpuState,
    pub instruction_budget: u64,
    pub loader_return: Option<GuestVirtualAddress>,
    pub timer: &'a dyn EngineTimer,
    pub events: VcpuEventState,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EngineExit {
    /// Requests one precise instruction through the configured semantic
    /// fallback engine. State and memory are canonical at `source`.
    InterpretOne {
        source: LocationDescriptor,
    },
    UnsupportedSemantics {
        source: LocationDescriptor,
        encoding: InstructionEncoding,
        disassembly: Box<str>,
        coverage_id: CoverageId,
    },
    ProfileDisabled {
        error: ProfileDisabledInstruction,
    },
    UnallocatedEncoding {
        error: UnallocatedEncoding,
    },
    FetchFault {
        fault: InstructionFetchFault,
    },
    BudgetExhausted,
    Safepoint,
    PendingEvent {
        mask: u32,
    },
    Scheduled {
        source: LocationDescriptor,
        request: SchedulerRequest,
    },
    ArchitecturalException {
        source: LocationDescriptor,
        kind: ExceptionKind,
        syndrome: Option<u64>,
    },
    SupervisorCall {
        source: LocationDescriptor,
        immediate: u32,
    },
    DataFault {
        source: LocationDescriptor,
        fault: DataAccessFault,
    },
    LoaderReturn {
        source: LocationDescriptor,
        result_code: u64,
    },
}

/// Precise synchronous exception presented to runtime policy.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct ExceptionDispatchRequest {
    source: LocationDescriptor,
    kind: ExceptionKind,
    syndrome: Option<u64>,
}

impl ExceptionDispatchRequest {
    #[must_use]
    pub const fn new(
        source: LocationDescriptor,
        kind: ExceptionKind,
        syndrome: Option<u64>,
    ) -> Self {
        Self {
            source,
            kind,
            syndrome,
        }
    }
    #[must_use]
    pub const fn source(self) -> LocationDescriptor {
        self.source
    }
    #[must_use]
    pub const fn kind(self) -> ExceptionKind {
        self.kind
    }
    #[must_use]
    pub const fn syndrome(self) -> Option<u64> {
        self.syndrome
    }
}

impl EngineExit {
    #[must_use]
    pub fn exception_dispatch_request(&self) -> Option<ExceptionDispatchRequest> {
        let (source, kind, syndrome) = match self {
            Self::ArchitecturalException {
                source,
                kind,
                syndrome,
            } => (*source, *kind, *syndrome),
            Self::SupervisorCall { source, immediate } => (
                *source,
                ExceptionKind::SupervisorCall,
                Some(u64::from(*immediate)),
            ),
            Self::DataFault { source, .. } => (*source, ExceptionKind::DataAbort, None),
            Self::ProfileDisabled { error } => (
                error.instruction.location,
                ExceptionKind::UndefinedInstruction,
                None,
            ),
            Self::UnallocatedEncoding { error } => (
                error.instruction.location,
                ExceptionKind::UndefinedInstruction,
                None,
            ),
            _ => return None,
        };
        Some(ExceptionDispatchRequest::new(source, kind, syndrome))
    }
}

impl Display for EngineExit {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::InterpretOne { source } => write!(formatter, "interpret-one source=[{source}]"),
            Self::UnsupportedSemantics {
                source,
                encoding,
                disassembly,
                coverage_id,
            } => write!(
                formatter,
                "unsupported-semantics source=[{source}] encoding={encoding} disassembly={disassembly} coverage={coverage_id}"
            ),
            Self::ProfileDisabled { error } => write!(formatter, "profile-disabled {error}"),
            Self::UnallocatedEncoding { error } => {
                write!(formatter, "unallocated-encoding {error}")
            }
            Self::FetchFault { fault } => write!(formatter, "fetch-fault {fault}"),
            Self::BudgetExhausted => formatter.write_str("budget-exhausted"),
            Self::Safepoint => formatter.write_str("safepoint"),
            Self::PendingEvent { mask } => write!(formatter, "pending-event mask=0x{mask:08x}"),
            Self::Scheduled { source, request } => {
                write!(formatter, "scheduled source=[{source}] request={request:?}")
            }
            Self::ArchitecturalException {
                source,
                kind,
                syndrome,
            } => write!(
                formatter,
                "architectural-exception source=[{source}] kind={kind:?} syndrome={syndrome:?}"
            ),
            Self::SupervisorCall { source, immediate } => write!(
                formatter,
                "supervisor-call source=[{source}] immediate={immediate:?}"
            ),
            Self::DataFault { source, fault } => {
                write!(formatter, "data-fault source=[{source}] fault={fault:?}")
            }
            Self::LoaderReturn {
                source,
                result_code,
            } => write!(
                formatter,
                "loader-return source=[{source}] result=0x{result_code:016x}"
            ),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExecutionReport {
    pub instructions_executed: u64,
    pub stop: EngineExit,
    pub context: RegisterContext,
}

impl Display for ExecutionReport {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "instructions={} stop=[{}] registers=[{}]",
            self.instructions_executed, self.stop, self.context
        )
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum EngineFaultKind {
    InvalidRequest,
    Internal,
    Unavailable,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EngineFault {
    pub engine: EngineId,
    pub kind: EngineFaultKind,
    pub instructions_executed: u64,
    pub message: Box<str>,
    pub context: Box<RegisterContext>,
}

impl Display for EngineFault {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "engine={} kind={:?} after={} message={} registers=[{}]",
            self.engine.get(),
            self.kind,
            self.instructions_executed,
            self.message,
            self.context
        )
    }
}

impl std::error::Error for EngineFault {}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct DomainRequest {
    pub domain: EngineDomainId,
    pub cpu: ProcessCpuContext,
}

/// Memory surface available to domains which retain native mappings.
pub trait DomainMemory: CpuMemory + CanonicalRangeTranslator {}

impl<T> DomainMemory for T where T: CpuMemory + CanonicalRangeTranslator {}

/// Complete canonical address-space view supplied at domain creation and
/// before executor re-entry after mapping changes.
#[derive(Clone, Copy)]
pub struct DomainMemoryBinding<'a> {
    pub address_space: AddressSpaceId,
    pub end_exclusive: GuestVirtualAddress,
    pub memory: &'a dyn DomainMemory,
    pub mapping_epoch: u64,
    pub invalidation_cursor: nixe_memory::MemoryInvalidationCursor,
}

pub trait EngineProvider: Send + Sync {
    fn descriptor(&self) -> EngineDescriptor;
    /// Probes the complete guest profile rather than a registry identity. This
    /// lets providers conservatively reject unknown architectural features.
    fn probe(&self, profile: GuestCpuProfile, required: EngineCapabilities) -> CapabilityReport;
    fn create_domain(&self, request: DomainRequest) -> Result<Box<dyn EngineDomain>, EngineFault>;
}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub enum EnginePreference {
    #[default]
    Auto,
    Explicit(EngineId),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EngineSelectionError {
    pub requested: EnginePreference,
    pub reports: Box<[CapabilityReport]>,
}

impl Display for EngineSelectionError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        write!(formatter, "no CPU engine satisfies {:?}", self.requested)?;
        for report in &self.reports {
            write!(formatter, "; {}: ", report.descriptor.name)?;
            if report.rejections.is_empty() {
                formatter.write_str("provider is unavailable")?;
            } else {
                for (index, rejection) in report.rejections.iter().enumerate() {
                    if index != 0 {
                        formatter.write_str(", ")?;
                    }
                    formatter.write_str(&rejection.detail)?;
                }
            }
        }
        Ok(())
    }
}
impl std::error::Error for EngineSelectionError {}

/// Deterministically ordered provider registry. `Auto` selects the first
/// available provider, so applications control policy through registration
/// order rather than host-dependent iteration order.
#[derive(Default)]
pub struct EngineRegistry {
    providers: Vec<Arc<dyn EngineProvider>>,
}

impl EngineRegistry {
    #[must_use]
    pub fn new(providers: impl IntoIterator<Item = Arc<dyn EngineProvider>>) -> Self {
        Self {
            providers: providers.into_iter().collect(),
        }
    }

    pub fn select(
        &self,
        profile: GuestCpuProfile,
        required: EngineCapabilities,
        preference: EnginePreference,
    ) -> Result<Arc<dyn EngineProvider>, EngineSelectionError> {
        match preference {
            EnginePreference::Auto => {
                let mut reports = Vec::new();
                for provider in &self.providers {
                    let report = validated_capability_report(provider.as_ref(), profile, required);
                    if report.available {
                        return Ok(Arc::clone(provider));
                    }
                    reports.push(report);
                }
                Err(EngineSelectionError {
                    requested: preference,
                    reports: reports.into_boxed_slice(),
                })
            }
            EnginePreference::Explicit(id) => {
                if let Some(provider) = self
                    .providers
                    .iter()
                    .find(|provider| provider.descriptor().id == id)
                {
                    let report = validated_capability_report(provider.as_ref(), profile, required);
                    if report.available {
                        return Ok(Arc::clone(provider));
                    }
                    return Err(EngineSelectionError {
                        requested: preference,
                        reports: Box::new([report]),
                    });
                }
                let reports = self
                    .providers
                    .iter()
                    .map(|provider| {
                        validated_capability_report(provider.as_ref(), profile, required)
                    })
                    .collect::<Vec<_>>();
                Err(EngineSelectionError {
                    requested: preference,
                    reports: reports.into_boxed_slice(),
                })
            }
        }
    }
}

fn validated_capability_report(
    provider: &dyn EngineProvider,
    profile: GuestCpuProfile,
    required: EngineCapabilities,
) -> CapabilityReport {
    let declared = provider.descriptor();
    let mut report = provider.probe(profile, required);
    if report.descriptor != declared
        || !declared.capabilities.is_coherent()
        || !declared.capabilities.contains(required)
        || !declared.capabilities.supports_profile(profile, required)
    {
        report.available = false;
        let mut rejections = Vec::from(report.rejections);
        rejections.push(CapabilityRejection {
            engine: declared.id,
            reason: CapabilityRejectionReason::MissingCapabilities,
            detail: "provider report disagrees with its descriptor or guest profile".into(),
        });
        report.rejections = rejections.into_boxed_slice();
    }
    report
}

pub trait EngineDomain: Send {
    fn descriptor(&self) -> EngineDescriptor;
    fn domain_id(&self) -> EngineDomainId;
    /// Creates executor-local state for an already-bound domain.
    fn create_executor(
        &mut self,
        executor: EngineExecutorId,
    ) -> Result<Box<dyn EngineExecutor>, EngineFault>;
    /// Binds the complete canonical address-space view before executors are
    /// created. Implementations must copy or retain safe backing objects; they
    /// must not retain the borrowed trait object.
    fn bind_memory(&mut self, _binding: DomainMemoryBinding<'_>) -> Result<(), EngineFault> {
        Ok(())
    }
    /// Closes new engine work and requests a bounded stop of provider-private
    /// activity. This operation must not wait for an executor or background
    /// task; runtime calls it before preparing and dropping executors.
    fn request_stop(&mut self) -> Result<(), EngineFault> {
        Ok(())
    }
    /// Permanently releases domain resources after every executor was dropped.
    /// Runtime process teardown calls [`EngineExecutor::prepare_shutdown`]
    /// before those drops; other direct owners must still drop all derived
    /// executor state. Implementations with external resources must make this
    /// idempotent.
    fn shutdown(&mut self) -> Result<(), EngineFault> {
        Ok(())
    }
}

/// Mutable execution resources leased exclusively to one host worker.
pub trait EngineExecutor: Send {
    fn descriptor(&self) -> EngineDescriptor;
    fn executor_id(&self) -> EngineExecutorId;
    /// Runs a bounded slice and commits canonical thread state before returning.
    fn run_slice(&mut self, request: RunRequest<'_>) -> Result<ExecutionReport, EngineFault>;
    /// Applies mapping/code invalidation before guest re-entry. Providers which
    /// advertise acknowledged invalidation must override this method.
    fn synchronize_invalidation(
        &mut self,
        cursor: nixe_memory::MemoryInvalidationCursor,
        state: &ThreadCpuState,
        memory: &dyn CpuMemory,
    ) -> Result<(), EngineFault> {
        let _ = memory;
        if !self.descriptor().capabilities.acknowledged_invalidation {
            return Ok(());
        }
        Err(EngineFault {
            engine: self.descriptor().id,
            kind: EngineFaultKind::InvalidRequest,
            instructions_executed: 0,
            message: format!(
                "engine advertises invalidation acknowledgement but cannot synchronize cursor {}",
                cursor.get()
            )
            .into_boxed_str(),
            context: Box::new(state.register_context()),
        })
    }
    /// Reconciles mappings and canonical backing before guest re-entry. Native
    /// engines override this hook; semantic engines inherit epoch handling.
    fn synchronize_address_space(
        &mut self,
        binding: DomainMemoryBinding<'_>,
        state: &ThreadCpuState,
    ) -> Result<(), EngineFault> {
        self.synchronize_invalidation(binding.invalidation_cursor, state, binding.memory)
    }
    /// Returns a cloneable control path which remains usable while a worker
    /// exclusively owns this executor.
    fn control(&self) -> Option<EngineControl> {
        None
    }
    /// Makes every executor-private derived mapping unreachable, acknowledges
    /// the final invalidation cursor, and clears processor-local state before
    /// ownership returns to the domain teardown path. Implementations may
    /// override this to stop a virtual CPU or reconcile provider-private state.
    fn prepare_shutdown(
        &mut self,
        binding: DomainMemoryBinding<'_>,
        state: &ThreadCpuState,
    ) -> Result<(), EngineFault> {
        self.synchronize_address_space(binding, state)?;
        self.clear_local_exclusive_reservation();
        Ok(())
    }
    /// Clears executor-local exclusive-reservation state at an explicit
    /// scheduler migration or context-switch boundary.
    fn clear_local_exclusive_reservation(&mut self);
}

/// Executes the canonical `InterpretOne` fallback contract. The helper forces
/// an exact one-instruction upper bound; architectural exits are returned
/// unchanged and therefore never acquire a synthesized fallthrough target.
pub fn run_interpret_one_fallback(
    executor: &mut dyn EngineExecutor,
    request: RunRequest<'_>,
) -> Result<ExecutionReport, EngineFault> {
    executor.run_slice(RunRequest {
        instruction_budget: 1,
        ..request
    })
}
