[package]
name = "nixe-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nixe-trace.workspace = true
getrandom.workspace = true
log.workspace = true
sha2.workspace = true
nixe-cpu.workspace = true
nixe-cpu-direct-memory.workspace = true
nixe-cpu-interpreter.workspace = true
nixe-cpu-jit.workspace = true
nixe-loader-executable.workspace = true
nixe-loader-content.workspace = true
nixe-loader-storage.workspace = true
nixe-loader-title.workspace = true
nixe-memory.workspace = true
nixe-scheduler.workspace = true

[dev-dependencies]
tempfile.workspace = true
