[package]
name = "nixe-cpu-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nixe-cpu = { path = "../crates/cpu" }
nixe-memory = { path = "../crates/memory" }

[[bin]]
name = "decoder"
path = "fuzz_targets/decoder.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
