//! Switch 1 Maxwell GPU frontend.
//!
//! This crate owns console GPU profile and command semantics. It depends only
//! on host-independent GPU contracts and never on Horizon or a host backend.

mod address_space;
mod capture;
mod channel;
mod engines;
mod execution;
mod gpfifo;
mod profile;
mod pushbuffer;
mod scheduler;
mod shader;

pub use address_space::{
    MAX_MAPPING_DUMP_ENTRIES, MaxwellAddressSpaceError, MaxwellAddressSpaceId,
    MaxwellAddressSpaceInitialization, MaxwellAllocationId, MaxwellGpuAccessError,
    MaxwellGpuAddressSpace, MaxwellGpuMapping, MaxwellMapRequest, MaxwellMappingDiagnostic,
    MaxwellMappingDump, MaxwellMappingId, MaxwellResolvedMapping, MaxwellResolvedRange,
    MaxwellSparseMapping, MaxwellSparseRemapRequest, MaxwellVaRegion, MaxwellVaReservation,
};
pub use capture::{
    MAXWELL_FRONTEND_CAPTURE_WORDS, MaxwellFrontendCapture, MaxwellFrontendCaptureError,
    MaxwellFrontendFailure, MaxwellFrontendReplay, capture_maxwell_frontend_dispatch,
    replay_maxwell_frontend_capture,
};
pub use channel::{
    MaxwellChannelError, MaxwellChannelFrontendState, MaxwellChannelId, MaxwellChannelOwner,
    MaxwellChannelPriority, MaxwellChannelSchedulingPolicy, MaxwellChannelTimeout,
    MaxwellChannelTimeslice, MaxwellGpuChannel, MaxwellMemoryManagerId, MaxwellObjectContext,
    MaxwellZCullBinding, MaxwellZCullMode,
};
pub use engines::{
    MAXWELL_BIND_GROUP_COUNT, MAXWELL_COLOR_TARGET_COUNT, MAXWELL_COMPUTE_CWD_REF_COUNTER_COUNT,
    MAXWELL_CONSTANT_BUFFER_SLOT_COUNT, MAXWELL_PIPELINE_SHADER_COUNT,
    MAXWELL_POLYGON_STIPPLE_PATTERN_WORD_COUNT, MAXWELL_SAMPLE_LOCATION_GROUP_COUNT,
    MAXWELL_SAMPLE_LOCATIONS_PER_GROUP, MAXWELL_SCISSOR_COUNT, MAXWELL_TESSELLATION_LOD_COUNT,
    MAXWELL_THREE_D_MME_CAPTURED_INSTRUCTION_WORDS, MAXWELL_THREE_D_MME_CAPTURED_START_ADDRESSES,
    MAXWELL_THREE_D_MME_EMITTED_METHOD_LIMIT, MAXWELL_THREE_D_MME_EXECUTION_INSTRUCTION_LIMIT,
    MAXWELL_THREE_D_PRIMITIVE_AREA_MAX, MAXWELL_THREE_D_SHADER_LOCAL_MEMORY_PER_WARP_SIZE_MAX,
    MAXWELL_THREE_D_SM_TIMEOUT_COUNTER_BIT_MAX, MAXWELL_TWO_D_CORRAL_SIZE_MAX,
    MAXWELL_TWO_D_NOTIFY_ADDRESS_UPPER_MAX, MAXWELL_VERTEX_ATTRIBUTE_COUNT,
    MAXWELL_VERTEX_STREAM_COUNT, MAXWELL_VIEWPORT_COUNT, MAXWELL_WINDOW_CLIP_COUNT,
    MaxwellComputeAddress, MaxwellComputeBindlessTextureConstantBufferSlot,
    MaxwellComputeCwdRefCounterIndex, MaxwellComputeCwdRefCounterState,
    MaxwellComputeCwdRefCounterValue, MaxwellComputeDescriptorPoolState,
    MaxwellComputeInlineToMemoryLaunch, MaxwellComputeInlineToMemoryLayout,
    MaxwellComputeInlineToMemoryPendingTransfer, MaxwellComputeInlineToMemoryState,
    MaxwellComputeInlineToMemoryUpload, MaxwellComputeLocalMemoryAllocation,
    MaxwellComputeLocalMemoryState, MaxwellComputeOperationTrigger, MaxwellComputeProgramState,
    MaxwellComputeRegister, MaxwellComputeRegisterOrigin, MaxwellComputeShaderCacheInvalidation,
    MaxwellComputeSmCount, MaxwellComputeSpaVersion, MaxwellComputeState, MaxwellComputeStateWrite,
    MaxwellComputeSynchronizationPlan, MaxwellComputeTriggeredOperation, MaxwellEngineCapability,
    MaxwellEngineDispatchError, MaxwellEngineMethodDispatch, MaxwellEngineMethodEffect,
    MaxwellEngineMethodMetadata, MaxwellEngineOperation, MaxwellEnginePacketDispatch,
    MaxwellHostSynchronizationOperation, MaxwellInlineToMemoryAddress, MaxwellInlineToMemoryLaunch,
    MaxwellInlineToMemoryPendingTransfer, MaxwellInlineToMemoryRegister,
    MaxwellInlineToMemorySemaphoreStructureSize, MaxwellInlineToMemoryState,
    MaxwellInlineToMemoryStateWrite, MaxwellInlineToMemoryUpload, MaxwellShaderCacheInvalidation,
    MaxwellThreeDAliasedLineWidthEnable, MaxwellThreeDAlphaFraction,
    MaxwellThreeDAntiAliasedLineEnable, MaxwellThreeDAttachmentReadiness,
    MaxwellThreeDAttributeDefaultVector, MaxwellThreeDAttributeDefaults,
    MaxwellThreeDAttributePointSize, MaxwellThreeDBegin, MaxwellThreeDBindGroupState,
    MaxwellThreeDBlendControlState, MaxwellThreeDBlendEnableCommon, MaxwellThreeDBlendFactor,
    MaxwellThreeDBlendFloatPixelKillEnable, MaxwellThreeDBlendOp,
    MaxwellThreeDBlendPerFormatEnable, MaxwellThreeDBlendZeroTimesAnythingIsZero,
    MaxwellThreeDClearState, MaxwellThreeDClearSurface, MaxwellThreeDClearSurfaceControl,
    MaxwellThreeDClipIdTestEnable, MaxwellThreeDColorCompressionMode, MaxwellThreeDColorMask,
    MaxwellThreeDColorReductionFp16Threshold, MaxwellThreeDColorReductionSrgb8Threshold,
    MaxwellThreeDColorReductionState, MaxwellThreeDColorReductionStateWrite,
    MaxwellThreeDColorReductionThresholdsEnable, MaxwellThreeDColorReductionThresholdsFp16,
    MaxwellThreeDColorReductionThresholdsSrgb8, MaxwellThreeDColorReductionThresholdsUnorm8,
    MaxwellThreeDColorReductionThresholdsUnorm10, MaxwellThreeDColorReductionThresholdsUnorm16,
    MaxwellThreeDColorTargetFormat, MaxwellThreeDColorTargetSelection,
    MaxwellThreeDColorTargetState, MaxwellThreeDCompareOp,
    MaxwellThreeDConditionalLoadConstantBuffer, MaxwellThreeDConservativeRasterEnable,
    MaxwellThreeDConstantBufferBinding, MaxwellThreeDConstantBufferLoadState,
    MaxwellThreeDConstantBufferSelectorState, MaxwellThreeDCoverageState,
    MaxwellThreeDCoverageStateWrite, MaxwellThreeDCsaaEnable, MaxwellThreeDCullFace,
    MaxwellThreeDDepthStencilFormat, MaxwellThreeDDepthStencilTargetState,
    MaxwellThreeDDepthTargetCount, MaxwellThreeDDescriptorPoolState,
    MaxwellThreeDDirectlyAddressableMemory, MaxwellThreeDDirtySubresource,
    MaxwellThreeDDirtySubresources, MaxwellThreeDEdgeFlag, MaxwellThreeDFillViaTriangleMode,
    MaxwellThreeDFixedFunctionRegister, MaxwellThreeDFixedFunctionState,
    MaxwellThreeDFixedFunctionValue, MaxwellThreeDFixedFunctionWrite,
    MaxwellThreeDFlushPendingWrites, MaxwellThreeDFrontFace, MaxwellThreeDGuestImageFormat,
    MaxwellThreeDHybridAntiAliasCentroid, MaxwellThreeDHybridAntiAliasControl,
    MaxwellThreeDImageKind, MaxwellThreeDImageLayout, MaxwellThreeDIndexBufferState,
    MaxwellThreeDIndexElementSize, MaxwellThreeDInlineConstantBufferUpload,
    MaxwellThreeDL2CacheEvictionPolicy, MaxwellThreeDLineState, MaxwellThreeDLineStateWrite,
    MaxwellThreeDLineStippleParameters, MaxwellThreeDLogicOp, MaxwellThreeDLoweredWork,
    MaxwellThreeDLoweringCache, MaxwellThreeDLoweringError, MaxwellThreeDLoweringPlan,
    MaxwellThreeDMappingReference, MaxwellThreeDMmeExecutionError, MaxwellThreeDMmeExecutionReport,
    MaxwellThreeDMmeInstruction, MaxwellThreeDMmeLoadError, MaxwellThreeDMmeRam,
    MaxwellThreeDMmeRamAddress, MaxwellThreeDMmeState, MaxwellThreeDMmeStateWrite,
    MaxwellThreeDOperationTrigger, MaxwellThreeDPatchSize, MaxwellThreeDPipelineBindingState,
    MaxwellThreeDPixelShaderClampRange, MaxwellThreeDPixelShaderSaturate,
    MaxwellThreeDPointCenterMode, MaxwellThreeDPointSize, MaxwellThreeDPointSpriteOrigin,
    MaxwellThreeDPointSpriteRMode, MaxwellThreeDPointSpriteSelect, MaxwellThreeDPolygonMode,
    MaxwellThreeDPreservedImageLayout, MaxwellThreeDPrimitiveCircularBufferThrottle,
    MaxwellThreeDPrimitiveState, MaxwellThreeDPrimitiveTopology, MaxwellThreeDProgramRegionState,
    MaxwellThreeDProvokingVertex, MaxwellThreeDPsOutputSampleMaskUsage,
    MaxwellThreeDRasterBoundingBox, MaxwellThreeDRasterBoundingBoxMode, MaxwellThreeDRasterState,
    MaxwellThreeDRawValue, MaxwellThreeDRectangle, MaxwellThreeDRegister,
    MaxwellThreeDRegisterOrigin, MaxwellThreeDRenderEnableMode, MaxwellThreeDRenderEnableState,
    MaxwellThreeDRenderEnableStateWrite, MaxwellThreeDRenderTargetIndexOffset,
    MaxwellThreeDRenderTargetLayer, MaxwellThreeDRenderTargetLayerControl,
    MaxwellThreeDRenderTargetState, MaxwellThreeDRenderTargetWrite,
    MaxwellThreeDReportSemaphoreControl, MaxwellThreeDReportSemaphoreOperation,
    MaxwellThreeDReportSemaphorePipelineLocation, MaxwellThreeDReportSemaphoreRelease,
    MaxwellThreeDReportSemaphoreState, MaxwellThreeDReportSemaphoreStateWrite,
    MaxwellThreeDReportSemaphoreStructureSize, MaxwellThreeDResolvedBuffer,
    MaxwellThreeDResolvedImage, MaxwellThreeDResolvedResource, MaxwellThreeDResolvedResources,
    MaxwellThreeDResourceAccess, MaxwellThreeDResourceAlias, MaxwellThreeDResourceError,
    MaxwellThreeDResourceRole, MaxwellThreeDRopL2CacheRequest, MaxwellThreeDRopL2CacheState,
    MaxwellThreeDRopL2CacheStateWrite, MaxwellThreeDSampleLocation,
    MaxwellThreeDSampleLocationGroup, MaxwellThreeDSampleMode, MaxwellThreeDSamplerBindingMode,
    MaxwellThreeDScissorState, MaxwellThreeDSeparateFragmentData, MaxwellThreeDShadeMode,
    MaxwellThreeDShaderBindingState, MaxwellThreeDShaderBindingWrite,
    MaxwellThreeDShaderCacheInvalidation, MaxwellThreeDShaderExecutionState,
    MaxwellThreeDShaderExecutionStateWrite, MaxwellThreeDShaderLocalMemoryPerWarpSize,
    MaxwellThreeDShaderLocalMemoryState, MaxwellThreeDShaderResourceUse, MaxwellThreeDShaderStage,
    MaxwellThreeDSmTimeoutCounterBit, MaxwellThreeDState, MaxwellThreeDStateWrite,
    MaxwellThreeDStencilOp, MaxwellThreeDSubtilingPerfKnobA, MaxwellThreeDSubtilingPerfKnobB,
    MaxwellThreeDSurfaceClipAxis, MaxwellThreeDSynchronizationError,
    MaxwellThreeDSynchronizationOperation, MaxwellThreeDSynchronizationPlan,
    MaxwellThreeDSynchronizationTrigger, MaxwellThreeDSyncpointCondition,
    MaxwellThreeDSyncpointIncrement, MaxwellThreeDTessellationLod,
    MaxwellThreeDTextureCacheInvalidation, MaxwellThreeDTextureCacheLines,
    MaxwellThreeDTextureCacheTarget, MaxwellThreeDTranslatedShader, MaxwellThreeDTranslatedShaders,
    MaxwellThreeDTriggeredOperation, MaxwellThreeDUnnegotiatedLoweringPlan, MaxwellThreeDUnorm8,
    MaxwellThreeDUnresolvedAddress, MaxwellThreeDVertexArrayPrimitiveRestartEnable,
    MaxwellThreeDVertexAssemblyState, MaxwellThreeDVertexAttributeFormat,
    MaxwellThreeDVertexComponentWidths, MaxwellThreeDVertexIdUsesArrayStart,
    MaxwellThreeDVertexInputState, MaxwellThreeDVertexInputWrite, MaxwellThreeDVertexNumericalType,
    MaxwellThreeDVertexStreamFormat, MaxwellThreeDVertexStreamState,
    MaxwellThreeDVertexStreamSubstituteState, MaxwellThreeDViewportClipControl,
    MaxwellThreeDViewportCoordinateSwizzle, MaxwellThreeDViewportPixelCenter,
    MaxwellThreeDViewportScaleOffsetEnable, MaxwellThreeDViewportState,
    MaxwellThreeDViewportSwizzleComponent, MaxwellThreeDViewportTransformState,
    MaxwellThreeDViewportZClipRange, MaxwellThreeDVisibleCallLimit, MaxwellThreeDWindowClipState,
    MaxwellThreeDWindowClipType, MaxwellThreeDZCompressionMode, MaxwellThreeDZCullBounds,
    MaxwellThreeDZCullEnable, MaxwellThreeDZCullRegionId, MaxwellThreeDZCullState,
    MaxwellThreeDZCullStateWrite, MaxwellThreeDZCullStatsEnable, MaxwellTwoDClipEnable,
    MaxwellTwoDColorKeyEnable, MaxwellTwoDNotifyAddressLower, MaxwellTwoDNotifyAddressUpper,
    MaxwellTwoDNotifyState, MaxwellTwoDNotifyStateWrite, MaxwellTwoDOperation,
    MaxwellTwoDPixelsFromMemoryCorralSize, MaxwellTwoDPixelsFromMemorySafeOverlap,
    MaxwellTwoDPixelsFromMemoryState, MaxwellTwoDPixelsFromMemoryStateWrite,
    MaxwellTwoDProcessingClusters, MaxwellTwoDRegister, MaxwellTwoDRegisterOrigin,
    MaxwellTwoDRenderEnableMode, MaxwellTwoDRenderEnableState, MaxwellTwoDRenderEnableStateWrite,
    MaxwellTwoDState, MaxwellTwoDStateWrite, commit_maxwell_engine_packet,
    dispatch_maxwell_engine_packet, dispatch_maxwell_engine_pushbuffer,
    lower_maxwell_compute_synchronization, lower_maxwell_three_d_synchronization,
    preflight_maxwell_engine_packet, preflight_maxwell_three_d_operation,
    preflight_maxwell_three_d_operation_unnegotiated, resolve_maxwell_three_d_resources,
};
pub use execution::{
    MaxwellSoftwareInitializationCompletion, MaxwellSoftwareInitializationError,
    MaxwellSubmissionExecutionError, MaxwellSubmissionExecutionPlan,
    MaxwellSubmissionExecutionStep, execute_maxwell_software_initialization,
    preflight_maxwell_submission_execution,
};
pub use gpfifo::{
    MAXWELL_GPFIFO_CAPTURE_SOURCES, MAXWELL_GPFIFO_ENTRY_SIZE, MaxwellDecodedGpfifoSubmission,
    MaxwellGpfifoCapture, MaxwellGpfifoCaptureSource, MaxwellGpfifoDecodeError, MaxwellGpfifoEntry,
    MaxwellGpfifoFetchMode, MaxwellGpfifoLevel, MaxwellGpfifoSourceError,
    MaxwellGpfifoSourceLocation, MaxwellGpfifoSubmissionMode, MaxwellGpfifoSubmitRequest,
    MaxwellGpfifoSyncMode, MaxwellInvalidGpfifoSubmission, MaxwellRetainedPushbuffer,
    MaxwellUnsupportedGpfifoSubmission, MaxwellValidatedGpfifoSubmission, decode_gpfifo_submission,
    resolve_gpfifo_submission,
};
pub use profile::{
    AddressBitCount, ChipName, GpuArchitecture, GpuBusType, GpuFeatureFlags, GpuImplementation,
    GpuPageSize, GpuPageSizeMask, GpuProfileId, GpuRevision, MaxwellAamVersion,
    MaxwellAamVersionRange, MaxwellCacheCapabilities, MaxwellChipsetIdentity,
    MaxwellClassCapabilities, MaxwellGpuProfile, MaxwellInterconnectCapabilities,
    MaxwellMemoryCapabilities, MaxwellProfileValidationError, MaxwellShaderCapabilities,
    MaxwellShaderProgramHeaderVersion, MaxwellShaderProgramHeaderVersionRange, MaxwellTopology,
    MaxwellVirtualAddressCapabilities, MaxwellZCullCapabilities, SWITCH_1_GM20B_PROFILE,
    ShaderVersion,
};
pub use pushbuffer::dispatch::{
    MAXWELL_LEGACY_MEM_OP_A_METHOD, MAXWELL_LEGACY_MEM_OP_B_METHOD, MAXWELL_SET_OBJECT_METHOD,
    MaxwellHostMemoryOperation, MaxwellHostMethod, MaxwellMethodDispatch,
    MaxwellMethodDispatchError, MaxwellMethodDispatchKind, MaxwellMethodSource,
    MaxwellPacketDispatch, MaxwellSetObjectTransition, commit_maxwell_packet,
    dispatch_maxwell_packet, dispatch_maxwell_pushbuffer, preflight_maxwell_packet,
};
pub use pushbuffer::packet::{
    MaxwellDecodedMethod, MaxwellDecodedMethodPacket, MaxwellDecodedPacket,
    MaxwellDecodedPushbuffer, MaxwellMethodPacketMode, MaxwellPushbufferControl,
    MaxwellPushbufferDecodeError, MaxwellPushbufferSubchannel, MaxwellPushbufferWord,
    decode_maxwell_pushbuffer, decode_maxwell_submission,
};
pub use scheduler::{
    MaxwellFrontendDispatch, MaxwellFrontendDispatchBoundary, MaxwellScheduleError,
    MaxwellScheduledSubmission, MaxwellScheduler, MaxwellSchedulerSequence,
    MaxwellSubmissionOrderingStage,
};
pub use shader::{
    MAXWELL_SHADER_PROGRAM_HEADER_SIZE, MAXWELL_SHADER_READ_LIMIT, MaxwellShaderProgramHeader,
    MaxwellShaderTranslationError,
};
