//! Declarative instruction decode tables.
//!
//! Decode patterns are compiled directly from Rust data instead of being
//! generated by `build.rs`. This keeps their source visible to rust-analyzer,
//! avoids generated-file drift, and makes builds deterministic by construction.
