[package]
name = "nixe-video-winit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytemuck.workspace = true
log.workspace = true
nixe-gpu.workspace = true
nixe-gpu-wgpu.workspace = true
nixe-video.workspace = true
wgpu.workspace = true
winit.workspace = true
