cmake_minimum_required(VERSION 3.16)
project(nixe_dynarmic LANGUAGES C CXX ASM)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_INSTALL_LIBDIR lib CACHE STRING "" FORCE)
set(DYNARMIC_FRONTENDS A64 CACHE STRING "" FORCE)
set(DYNARMIC_TESTS OFF CACHE BOOL "" FORCE)
set(DYNARMIC_USE_BUNDLED_EXTERNALS ON CACHE BOOL "" FORCE)
set(DYNARMIC_WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)
add_subdirectory(../../../vendor/dynarmic dynarmic)
target_compile_definitions(dynarmic PRIVATE DYNARMIC_EXTERNAL_FAULT_HANDLER)
add_library(nixe_dynarmic STATIC bridge.cpp)
target_link_libraries(nixe_dynarmic PRIVATE dynarmic merry::mcl)
install(TARGETS nixe_dynarmic ARCHIVE DESTINATION lib)
if(TARGET Zycore)
    install(TARGETS Zycore ARCHIVE DESTINATION lib)
endif()

if(NIXE_PERFORMANCE_COUNTERS)
  target_compile_definitions(nixe_dynarmic PRIVATE NIXE_PERFORMANCE_COUNTERS)
endif()
